// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from wallet.djinni

#ifndef DJINNI_GENERATED_ADDRESS_HPP
#define DJINNI_GENERATED_ADDRESS_HPP

#include "../utils/optional.hpp"
#include <memory>
#include <string>

namespace ledger { namespace core { namespace api {

class BitcoinLikeAddress;

class Address {
public:
    virtual ~Address() {}

    virtual std::experimental::optional<std::string> getDerivationPath() = 0;

    virtual std::experimental::optional<std::string> toString() = 0;

    virtual std::shared_ptr<BitcoinLikeAddress> asBitcoinLikeAddress() = 0;

    static std::shared_ptr<Address> parse(const std::string & address);
};

} } }  // namespace ledger::core::api
#endif //DJINNI_GENERATED_ADDRESS_HPP
