// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from configuration.djinni

#ifndef DJINNI_GENERATED_POOLCONFIGURATION_HPP
#define DJINNI_GENERATED_POOLCONFIGURATION_HPP

#include <string>

namespace ledger { namespace core { namespace api {

/**TODO */
class PoolConfiguration {
public:
    virtual ~PoolConfiguration() {}

    static std::string const DATABASE_NAME;

    /**
     * Enable internal logging.
     *
     * Set to true by default.
     */
    static std::string const ENABLE_INTERNAL_LOGGING;
};

} } }  // namespace ledger::core::api
#endif //DJINNI_GENERATED_POOLCONFIGURATION_HPP
