// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from wallet.djinni

#ifndef DJINNI_GENERATED_NJSADDRESS_HPP
#define DJINNI_GENERATED_NJSADDRESS_HPP


#include "../include/../utils/optional.hpp"
#include "NJSBitcoinLikeAddressCpp.hpp"
#include <memory>
#include <string>

#include <nan.h>
#include <node.h>
#include "../include/Address.hpp"

using namespace v8;
using namespace node;
using namespace std;
using namespace ledger::core::api;

class NJSAddress: public Nan::ObjectWrap {
public:

    static void Initialize(Local<Object> target);
    virtual ~NJSAddress() {};
    NJSAddress(const std::shared_ptr<ledger::core::api::Address> &iAddress):_Address(iAddress){};

    static Handle<Object> wrap(const std::shared_ptr<ledger::core::api::Address> &object);
    static Nan::Persistent<ObjectTemplate> Address_prototype;
    std::shared_ptr<ledger::core::api::Address> getCppImpl(){return _Address;};

private:
    static NAN_METHOD(getDerivationPath);

    static NAN_METHOD(toString);

    static NAN_METHOD(asBitcoinLikeAddress);

    static NAN_METHOD(parse);

    static NAN_METHOD(New);

    static NAN_METHOD(isNull);
    std::shared_ptr<ledger::core::api::Address> _Address;
};
#endif //DJINNI_GENERATED_NJSADDRESS_HPP
