// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from wallet.djinni

#ifndef DJINNI_GENERATED_NJSCOSMOSCONFIGURATIONDEFAULTS_HPP
#define DJINNI_GENERATED_NJSCOSMOSCONFIGURATIONDEFAULTS_HPP


#include <memory>

#include <nan.h>
#include <node.h>
#include "../include/CosmosConfigurationDefaults.hpp"

using namespace v8;
using namespace node;
using namespace std;
using namespace ledger::core::api;

class NJSCosmosConfigurationDefaults final {
public:

    static void Initialize(Local<Object> target);
    NJSCosmosConfigurationDefaults() = delete;

    static Local<Object> wrap(const std::shared_ptr<ledger::core::api::CosmosConfigurationDefaults> &object);
    static Nan::Persistent<ObjectTemplate> CosmosConfigurationDefaults_prototype;

private:
    static NAN_METHOD(New);

    static NAN_METHOD(isNull);
};
#endif //DJINNI_GENERATED_NJSCOSMOSCONFIGURATIONDEFAULTS_HPP
