// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from database.djinni

#ifndef DJINNI_GENERATED_NJSDATABASEERROR_HPP
#define DJINNI_GENERATED_NJSDATABASEERROR_HPP


#include <string>

#include <nan.h>
#include <node.h>
#include "../include/DatabaseError.hpp"

using namespace v8;
using namespace node;
using namespace std;
using namespace ledger::core::api;

class NJSDatabaseError: public ledger::core::api::DatabaseError {
public:

    static void Initialize(Local<Object> target);

    static Local<Object> wrap(const std::shared_ptr<ledger::core::api::DatabaseError> &object);
    static Nan::Persistent<ObjectTemplate> DatabaseError_prototype;
    ~NJSDatabaseError()
    {
        njs_impl.Reset();
    };
    NJSDatabaseError(Local<Object> njs_implementation){njs_impl.Reset(njs_implementation);};

    /**
     * Get a human readable error message.
     * @return The error message.
     */
    std::string getMessage();

private:
    /**
     * Get a human readable error message.
     * @return The error message.
     */
    static NAN_METHOD(getMessage);

    static NAN_METHOD(New);

    Nan::Persistent<Object> njs_impl;
};
#endif //DJINNI_GENERATED_NJSDATABASEERROR_HPP
