// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from ethereum_like_wallet.djinni

#ifndef DJINNI_GENERATED_NJSETHEREUMLIKEACCOUNT_HPP
#define DJINNI_GENERATED_NJSETHEREUMLIKEACCOUNT_HPP


#include "NJSERC20LikeAccountCpp.hpp"
#include "NJSEthereumLikeTransactionBuilderCpp.hpp"
#include "NJSEthereumLikeTransactionCpp.hpp"
#include "NJSStringCallback.hpp"
#include <cstdint>
#include <memory>
#include <vector>

#include <nan.h>
#include <node.h>
#include "../include/EthereumLikeAccount.hpp"

using namespace v8;
using namespace node;
using namespace std;
using namespace ledger::core::api;

class NJSEthereumLikeAccount final {
public:

    static void Initialize(Local<Object> target);
    NJSEthereumLikeAccount() = delete;

    static Local<Object> wrap(const std::shared_ptr<ledger::core::api::EthereumLikeAccount> &object);
    static Nan::Persistent<ObjectTemplate> EthereumLikeAccount_prototype;

private:
    /** Send a raw (binary) transaction on the Ethereum blockchain. */
    static NAN_METHOD(broadcastRawTransaction);

    /** Send a transaction on the Ethereum blockchain. */
    static NAN_METHOD(broadcastTransaction);

    /** Get a builder object to construct transactions. */
    static NAN_METHOD(buildTransaction);

    /** Get the list of ERC20 accounts associated with this Ethereum account. */
    static NAN_METHOD(getERC20Accounts);

    static NAN_METHOD(New);

    static NAN_METHOD(isNull);
};
#endif //DJINNI_GENERATED_NJSETHEREUMLIKEACCOUNT_HPP
