// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from callback.djinni

#include "NJSExtendedKeyAccountCreationInfoCallback.hpp"
#include "NJSObjectWrapper.hpp"

using namespace v8;
using namespace node;
using namespace std;

void NJSExtendedKeyAccountCreationInfoCallback::onCallback(const std::experimental::optional<::ledger::core::api::ExtendedKeyAccountCreationInfo> & result, const std::experimental::optional<::ledger::core::api::Error> & error)
{
    Nan::HandleScope scope;
    //Wrap parameters
    Local<Value> arg_0;
    if(result)
    {
        auto arg_0_optional = (result).value();
        auto arg_0_tmp = Nan::New<Object>();
        auto arg_0_tmp_1 = Nan::New<Int32>(arg_0_optional.index);
        Nan::DefineOwnProperty(arg_0_tmp, Nan::New<String>("index").ToLocalChecked(), arg_0_tmp_1);
        Local<Array> arg_0_tmp_2 = Nan::New<Array>();
        for(size_t arg_0_tmp_2_id = 0; arg_0_tmp_2_id < arg_0_optional.owners.size(); arg_0_tmp_2_id++)
        {
            auto arg_0_tmp_2_elem = Nan::New<String>(arg_0_optional.owners[arg_0_tmp_2_id]).ToLocalChecked();
            Nan::Set(arg_0_tmp_2, (int)arg_0_tmp_2_id,arg_0_tmp_2_elem);
        }

        Nan::DefineOwnProperty(arg_0_tmp, Nan::New<String>("owners").ToLocalChecked(), arg_0_tmp_2);
        Local<Array> arg_0_tmp_3 = Nan::New<Array>();
        for(size_t arg_0_tmp_3_id = 0; arg_0_tmp_3_id < arg_0_optional.derivations.size(); arg_0_tmp_3_id++)
        {
            auto arg_0_tmp_3_elem = Nan::New<String>(arg_0_optional.derivations[arg_0_tmp_3_id]).ToLocalChecked();
            Nan::Set(arg_0_tmp_3, (int)arg_0_tmp_3_id,arg_0_tmp_3_elem);
        }

        Nan::DefineOwnProperty(arg_0_tmp, Nan::New<String>("derivations").ToLocalChecked(), arg_0_tmp_3);
        Local<Array> arg_0_tmp_4 = Nan::New<Array>();
        for(size_t arg_0_tmp_4_id = 0; arg_0_tmp_4_id < arg_0_optional.extendedKeys.size(); arg_0_tmp_4_id++)
        {
            auto arg_0_tmp_4_elem = Nan::New<String>(arg_0_optional.extendedKeys[arg_0_tmp_4_id]).ToLocalChecked();
            Nan::Set(arg_0_tmp_4, (int)arg_0_tmp_4_id,arg_0_tmp_4_elem);
        }

        Nan::DefineOwnProperty(arg_0_tmp, Nan::New<String>("extendedKeys").ToLocalChecked(), arg_0_tmp_4);

        arg_0 = arg_0_tmp;
    }

    Local<Value> arg_1;
    if(error)
    {
        auto arg_1_optional = (error).value();
        auto arg_1_tmp = Nan::New<Object>();
        auto arg_1_tmp_1 = Nan::New<Integer>((int)arg_1_optional.code);
        Nan::DefineOwnProperty(arg_1_tmp, Nan::New<String>("code").ToLocalChecked(), arg_1_tmp_1);
        auto arg_1_tmp_2 = Nan::New<String>(arg_1_optional.message).ToLocalChecked();
        Nan::DefineOwnProperty(arg_1_tmp, Nan::New<String>("message").ToLocalChecked(), arg_1_tmp_2);

        arg_1 = arg_1_tmp;
    }

    auto local_resolver = Nan::New<Promise::Resolver>(pers_resolver);
    if(error)
    {
        auto rejected = local_resolver->Reject(Nan::GetCurrentContext(), arg_1);
        rejected.FromJust();
    }
    else
    {
        auto resolve = local_resolver->Resolve(Nan::GetCurrentContext(), arg_0);
        resolve.FromJust();
    }
}

NAN_METHOD(NJSExtendedKeyAccountCreationInfoCallback::New) {
    //Only new allowed
    if(!info.IsConstructCall())
    {
        return Nan::ThrowError("NJSExtendedKeyAccountCreationInfoCallback function can only be called as constructor (use New)");
    }

    auto resolver = v8::Promise::Resolver::New(Nan::GetCurrentContext()).ToLocalChecked();
    auto node_instance = std::make_shared<NJSExtendedKeyAccountCreationInfoCallback>(resolver);
    djinni::js::ObjectWrapper<NJSExtendedKeyAccountCreationInfoCallback>::Wrap(node_instance, info.This());
    info.GetReturnValue().Set(info.This());
}


Nan::Persistent<ObjectTemplate> NJSExtendedKeyAccountCreationInfoCallback::ExtendedKeyAccountCreationInfoCallback_prototype;

Local<Object> NJSExtendedKeyAccountCreationInfoCallback::wrap(const std::shared_ptr<ledger::core::api::ExtendedKeyAccountCreationInfoCallback> &object) {
    Nan::EscapableHandleScope scope;
    Local<ObjectTemplate> local_prototype = Nan::New(ExtendedKeyAccountCreationInfoCallback_prototype);

    Local<Object> obj;
    if(!local_prototype.IsEmpty())
    {
        obj = local_prototype->NewInstance(Nan::GetCurrentContext()).ToLocalChecked();
        djinni::js::ObjectWrapper<ledger::core::api::ExtendedKeyAccountCreationInfoCallback>::Wrap(object, obj);
    }
    else
    {
        Nan::ThrowError("NJSExtendedKeyAccountCreationInfoCallback::wrap: object template not valid");
    }
    return scope.Escape(obj);
}

void NJSExtendedKeyAccountCreationInfoCallback::Initialize(Local<Object> target) {
    Nan::HandleScope scope;

    Local<FunctionTemplate> func_template = Nan::New<FunctionTemplate>(NJSExtendedKeyAccountCreationInfoCallback::New);
    Local<ObjectTemplate> objectTemplate = func_template->InstanceTemplate();
    objectTemplate->SetInternalFieldCount(1);

    func_template->SetClassName(Nan::New<String>("NJSExtendedKeyAccountCreationInfoCallback").ToLocalChecked());
    Nan::SetPrototypeMethod(func_template,"New", New);
    //Set object prototype
    ExtendedKeyAccountCreationInfoCallback_prototype.Reset(objectTemplate);

    //Add template to target
    Nan::Set(target, Nan::New<String>("NJSExtendedKeyAccountCreationInfoCallback").ToLocalChecked(), Nan::GetFunction(func_template).ToLocalChecked());
}
