// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from ripple_like_wallet.djinni

#ifndef DJINNI_GENERATED_NJSRIPPLECONFIGURATIONDEFAULTS_HPP
#define DJINNI_GENERATED_NJSRIPPLECONFIGURATIONDEFAULTS_HPP


#include <memory>

#include <nan.h>
#include <node.h>
#include "../include/RippleConfigurationDefaults.hpp"

using namespace v8;
using namespace node;
using namespace std;
using namespace ledger::core::api;

class NJSRippleConfigurationDefaults final {
public:

    static void Initialize(Local<Object> target);
    NJSRippleConfigurationDefaults() = delete;

    static Local<Object> wrap(const std::shared_ptr<ledger::core::api::RippleConfigurationDefaults> &object);
    static Nan::Persistent<ObjectTemplate> RippleConfigurationDefaults_prototype;

private:
    static NAN_METHOD(New);

    static NAN_METHOD(isNull);
};
#endif //DJINNI_GENERATED_NJSRIPPLECONFIGURATIONDEFAULTS_HPP
