// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from stellar_like_wallet.djinni

#ifndef DJINNI_GENERATED_NJSSTELLARLIKEBLOCK_HPP
#define DJINNI_GENERATED_NJSSTELLARLIKEBLOCK_HPP


#include <memory>

#include <nan.h>
#include <node.h>
#include "../include/StellarLikeBlock.hpp"

using namespace v8;
using namespace node;
using namespace std;
using namespace ledger::core::api;

class NJSStellarLikeBlock final {
public:

    static void Initialize(Local<Object> target);
    NJSStellarLikeBlock() = delete;

    static Local<Object> wrap(const std::shared_ptr<ledger::core::api::StellarLikeBlock> &object);
    static Nan::Persistent<ObjectTemplate> StellarLikeBlock_prototype;

private:
    static NAN_METHOD(New);

    static NAN_METHOD(isNull);
};
#endif //DJINNI_GENERATED_NJSSTELLARLIKEBLOCK_HPP
