// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from stellar_like_wallet.djinni

#include "NJSStellarLikeBlockCpp.hpp"
#include "NJSObjectWrapper.hpp"

using namespace v8;
using namespace node;
using namespace std;


NAN_METHOD(NJSStellarLikeBlock::New) {
    //Only new allowed
    if(!info.IsConstructCall())
    {
        return Nan::ThrowError("NJSStellarLikeBlock function can only be called as constructor (use New)");
    }
    info.GetReturnValue().Set(info.This());
}


Nan::Persistent<ObjectTemplate> NJSStellarLikeBlock::StellarLikeBlock_prototype;

Local<Object> NJSStellarLikeBlock::wrap(const std::shared_ptr<ledger::core::api::StellarLikeBlock> &object) {
    Nan::EscapableHandleScope scope;
    Local<ObjectTemplate> local_prototype = Nan::New(StellarLikeBlock_prototype);

    Local<Object> obj;
    if(!local_prototype.IsEmpty())
    {
        obj = local_prototype->NewInstance(Nan::GetCurrentContext()).ToLocalChecked();
        djinni::js::ObjectWrapper<ledger::core::api::StellarLikeBlock>::Wrap(object, obj);
    }
    else
    {
        Nan::ThrowError("NJSStellarLikeBlock::wrap: object template not valid");
    }
    return scope.Escape(obj);
}

NAN_METHOD(NJSStellarLikeBlock::isNull) {
    auto cpp_implementation = djinni::js::ObjectWrapper<ledger::core::api::StellarLikeBlock>::Unwrap(info.This());
    auto isNull = !cpp_implementation ? true : false;
    return info.GetReturnValue().Set(Nan::New<Boolean>(isNull));
}

void NJSStellarLikeBlock::Initialize(Local<Object> target) {
    Nan::HandleScope scope;

    Local<FunctionTemplate> func_template = Nan::New<FunctionTemplate>(NJSStellarLikeBlock::New);
    Local<ObjectTemplate> objectTemplate = func_template->InstanceTemplate();
    objectTemplate->SetInternalFieldCount(1);

    func_template->SetClassName(Nan::New<String>("NJSStellarLikeBlock").ToLocalChecked());

    //SetPrototypeMethod all methods
    Nan::SetPrototypeMethod(func_template,"isNull", isNull);
    //Set object prototype
    StellarLikeBlock_prototype.Reset(objectTemplate);

    //Add template to target
    target->Set(Nan::New<String>("NJSStellarLikeBlock").ToLocalChecked(), func_template->GetFunction(Nan::GetCurrentContext()).ToLocalChecked());
}
